micronaut:
  application:
    name: encryptService
  server:
    port: -1
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
---
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 1
---
datasources:
  default:
    url: jdbc:mysql://localhost:3306/demo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
    schema-generate: CREATE_DROP
    dialect: MYSQL
